apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gameserver-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: game
    spec:
      hostNetwork: true
      imagePullSecrets:
        - name: johnpsecret
      containers:
        - name: unetserver
          image: johnp.azurecr.io/userver:latest
          imagePullPolicy: Always